# Generated by Django 5.0.2 on 2024-02-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('Bookname', models.CharField(max_length=20)),
                ('Bookauthor', models.CharField(max_length=50)),
                ('Bookprice', models.IntegerField()),
                ('Bookgenre', models.CharField(max_length=20)),
            ],
        ),
    ]
